### ISSUE TITLE
如何才能立即从屏幕中移除弹幕 ，不是隐藏的那种

### ISSUE THREAD

**Issue by erleizh** [hpdx/DanmukuLight#11]
我是在一个AdapterView 中使用的弹幕 。 会有重用问题

**Comment by hpdx** [comment]
@lll-01 使用DanMuView的release()方法，移除DanMuView中所有弹道中的所有弹幕。

**Comment by erleizh** [comment]
如果使用 release() 移除的话 , 重新添加会无法显示 

我的解决办法是

```

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        if (onDanMuViewTouchListeners == null) {
            onDanMuViewTouchListeners = new ArrayList<>();
        }
        if (danMuController == null) {
            danMuController = new DanMuController(this);
        }
    }

    public void init() {
        onDanMuViewTouchListeners = new ArrayList<>();
        if (danMuController == null) {
            danMuController = new DanMuController(this);
        }
    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        release();
    }
```

**Comment by chengzhijun0706** [comment]
@lll-01 是修改DanMuView成你写的这样,然后调用release和prepare么

**Comment by erleizh** [comment]
@chengzhijun0706  release() 不用调用了 , 在onDetachedFromWindow()的时候会自动 release() , 在使用的时候调用prepare就可以了 , 你看看这样写符不符合你的需求 , 可以改改

**Comment by chengzhijun0706** [comment]
@lll-01 我要实现一个多屏滑动的,每一屏有这个弹幕view,但在加载下一页的时候,上一页的弹幕无法销毁掉,下一页也需要加新的

**Comment by erleizh** [comment]
@chengzhijun0706 如果同一时间只需要显示一个 DanMuView 你可以考虑在每一个ItemView 里面放一个FrameLayout , 然后动态往里面添加DanMuView 的实例, 这样的话你用上面的那种写法是可以的,  但是有个问题就是你如果划回来 , 弹幕又是重新加载了 ,

**Comment by chengzhijun0706** [comment]
@lll-01 如果多页共用一个的话,清空操作很麻烦么?

**Comment by erleizh** [comment]
@chengzhijun0706 不太麻烦 .  你也可以直接放DanMuView , 反正没有启动DanMu 的话貌似资源占用不太大  ? 我也没仔细看

**Comment by chengzhijun0706** [comment]
@lll-01 如果是现在已经有弹幕在飘了,但是我切到下一页的时候,要吧这个清空该怎么弄呢

**Comment by erleizh** [comment]
@chengzhijun0706 

~~~
    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        release();
    }
~~~

你这样没法销毁吗 . 我也没用这个库 ,

**Comment by chengzhijun0706** [comment]
@lll-01 没有,因为这个弹幕的view是一直存在的,每次切换的是下面的viewpager,

**Comment by erleizh** [comment]
@chengzhijun0706 那你做ViewPager 的监听吧 ,

**Comment by chengzhijun0706** [comment]
@lll-01 我现在就是viewpage监听了,但是调用release后就显示不了了

**Comment by erleizh** [comment]
@chengzhijun0706  对呀  , 因为它release 之后就把
```
danMuController 
onDanMuViewTouchListeners 
```
全置为null了嘛 , 你得找个时机重新创建 , 改他源码 . 我是在添加到窗体的时候重新初始化的

**Comment by chengzhijun0706** [comment]
@lll-01 好的,明白了,谢谢了

**Comment by chengzhijun0706** [comment]
@lll-01 如果调用release可以立刻吧正在显示的弹幕也干掉么

**Comment by erleizh** [comment]
@chengzhijun0706  不知道 , 应该可以吧 , 毕竟我没用 , 你得问作者

**Comment by chengzhijun0706** [comment]
@lll-01 那你目前使用的是哪个库呢

**Comment by erleizh** [comment]
bilibili的 ,

**Comment by chengzhijun0706** [comment]
一开始也是使用的那个,那个库自定义太繁琐,后来从新找的

**Comment by erleizh** [comment]
@chengzhijun0706 其实也还好 , 我已开始以为需要重新实现一个 JsonDanmakuPaser , 后来发现直接使用BaseDanmakuPaser  就可以了 然后直接使用addDanmaku就可以了 , 要随机的话 直接加一个随机的延迟时间就行

**Comment by chengzhijun0706** [comment]
@lll-01 主要我们的需求是没有弹幕源,只是现发现显示就可以,不需要保存,感觉功能有些冗余

**Comment by muyoumingzi** [comment]
> @chengzhijun0706 其实也还好 , 我已开始以为需要重新实现一个 JsonDanmakuPaser , 后来发现直接使用BaseDanmakuPaser 就可以了 然后直接使用addDanmaku就可以了 , 要随机的话 直接加一个随机的延迟时间就行



> 如果使用 release() 移除的话 , 重新添加会无法显示
> 
> 我的解决办法是
> 
> ```
> 
>     @Override
>     protected void onAttachedToWindow() {
>         super.onAttachedToWindow();
>         if (onDanMuViewTouchListeners == null) {
>             onDanMuViewTouchListeners = new ArrayList<>();
>         }
>         if (danMuController == null) {
>             danMuController = new DanMuController(this);
>         }
>     }
> 
>     public void init() {
>         onDanMuViewTouchListeners = new ArrayList<>();
>         if (danMuController == null) {
>             danMuController = new DanMuController(this);
>         }
>     }
> 
>     @Override
>     protected void onDetachedFromWindow() {
>         super.onDetachedFromWindow();
>         release();
>     }
> ```

如何清空所有弹幕添加新的呢？需求是根据条件筛选弹幕，需要立刻清空当前的弹幕并显示筛选出来的弹幕。。请问你有什么思路么，这个库看来作者是不维护了。
