### ISSUE TITLE
请问怎么设置弹幕循环播放

### ISSUE THREAD

**Issue by Nidy** [hpdx/DanmukuLight#19]
如题

**Comment by hpdx** [comment]
@Nidy 目前暂不支持弹幕循环播放，你要想循环播放，也不是不可以，把相同的弹幕对象反复添加到弹幕队列里即可。

**Comment by Nidy** [comment]
我是这样处理的，当danMuViewQueue队列里没有弹幕的时候，加个监听完成的callback，再重新把之前的弹幕加到队列里
private synchronized void drawEveryElement(ArrayList<DanMuModel> danMuViewQueue, Canvas canvas) {
        mIsDrawing = true;
        if (danMuViewQueue == null || danMuViewQueue.size() == 0) {
            return;
        }

        for (int i = 0; i < (danMuViewQueue.size() > MAX_COUNT_IN_SCREEN
                ? MAX_COUNT_IN_SCREEN : danMuViewQueue.size()); i++) {
            DanMuModel danMuView = danMuViewQueue.get(i);
            if (danMuView.isAlive()) {
                DanMuPainter danMuPainter = getPainter(danMuView);
                DanMuChannel danMuChannel = mDanMuChannels[danMuView.getChannelIndex()];
                danMuChannel.dispatch(danMuView);
                if (danMuView.isAttached()) {
                    performDraw(danMuView, danMuPainter, canvas, danMuChannel);
                }
            } else {
                danMuViewQueue.remove(i);
                i--;
                if (mCompleteListener != null && isDrawnQueueEmpty()) {
                    mCompleteListener.onComplete();
                }
            }
        }
        mIsDrawing = false;
    }

**Comment by muyoumingzi** [comment]
> 我是这样处理的，当danMuViewQueue队列里没有弹幕的时候，加个监听完成的callback，再重新把之前的弹幕加到队列里 private synchronized void drawEveryElement(ArrayList danMuViewQueue, Canvas canvas) { mIsDrawing = true; if (danMuViewQueue == null || danMuViewQueue.size() == 0) { return; }
> 
> ```
>     for (int i = 0; i < (danMuViewQueue.size() > MAX_COUNT_IN_SCREEN
>             ? MAX_COUNT_IN_SCREEN : danMuViewQueue.size()); i++) {
>         DanMuModel danMuView = danMuViewQueue.get(i);
>         if (danMuView.isAlive()) {
>             DanMuPainter danMuPainter = getPainter(danMuView);
>             DanMuChannel danMuChannel = mDanMuChannels[danMuView.getChannelIndex()];
>             danMuChannel.dispatch(danMuView);
>             if (danMuView.isAttached()) {
>                 performDraw(danMuView, danMuPainter, canvas, danMuChannel);
>             }
>         } else {
>             danMuViewQueue.remove(i);
>             i--;
>             if (mCompleteListener != null && isDrawnQueueEmpty()) {
>                 mCompleteListener.onComplete();
>             }
>         }
>     }
>     mIsDrawing = false;
> }
> ```

你好，请问具体是从哪里重新添加队列呢，看了一遍源码没太看懂从哪里加，不忙的话希望可以解答一下，谢谢了。
