### ISSUE TITLE
这种样式的弹幕怎么实现？

### ISSUE THREAD

**Issue by hukejia** [hpdx/DanmukuLight#2]
![7_pxfizk2 h ix0_vpw](https://cloud.githubusercontent.com/assets/13723905/21479422/432a1706-cb8f-11e6-892d-00fc1c842bec.png)

**Comment by hpdx** [comment]
@hukejia 
1、下载源码，找到DanMuPainter类，其完整路径是com.anbetter.danmuku.model.painter.DanMuPainter
2、原来的draw方法实现代码如下：
 protected void draw(Canvas canvas, DanMuModel danMuView, DanMuChannel danMuChannel) {
        if (danMuView.textBackground != null) {
            drawTextBackground(danMuView, canvas, danMuChannel);
        }

        if (danMuView.avatar != null) {
            drawAvatar(danMuView, canvas, danMuChannel);
        }

        if(danMuView.avatarStrokes) {
            drawAvatarStrokes(danMuView, canvas, danMuChannel);
        }

        if (danMuView.levelBitmap != null) {
            drawLevel(danMuView, canvas, danMuChannel);
        }

        if (!TextUtils.isEmpty(danMuView.levelText)) {
            drawLevelText(danMuView, canvas, danMuChannel);
        }

        if (!TextUtils.isEmpty(danMuView.text)) {
            drawText(danMuView, canvas, danMuChannel);
        }
    }

3、你可以修改draw方法中的具体实现，已达到你想要的效果
4、修改DanMuDispatcher类中的measure(DanMuModel danMuView, DanMuChannel danMuChannel)方法，该方法的主要功能是测量弹幕的长度和高度。
