### ISSUE TITLE
没有弹幕的时候，你还在不断的dispatch

### ISSUE THREAD

**Issue by lyx0224** [hpdx/DanmukuLight#21]
如题
希望作者改进下。。

**Comment by hpdx** [comment]
@lyx0224 
你好，感谢反馈问题。
1、弹幕的分发是在DanMuDispatcher类里dispatch(DanMuModel danMuView, DanMuChannel[] danMuChannels)方法里，在弹幕队里没有弹幕时，该方法是不会执行的，你可以试试。

2、你反馈的问题实际上是这个库里的一个检测机制，每个100毫秒检测一次，检查弹幕队里是否有新的弹幕加入。可以改成使用队列的阻塞机制，我抽时间优化下。
