### ISSUE TITLE
关于DanmuModel方法setspeed的问题

### ISSUE THREAD

**Issue by Skilling-Kiss** [hpdx/DanmukuLight#28]
好像是没做完？设置什么都没效果啊，而且设置0也不会停止

**Comment by hpdx** [comment]
@Skilling-Kiss  
1、弹幕的速度控制在DanMuChannel类里，目前是每100毫秒移动3个像素。
2、至于DanmuModel类里setSpeed()方法的问题，后面我抽时间完善下

**Comment by Skilling-Kiss** [comment]
之前就已经搞定可以修改速度了，不过弹幕速度快慢控制比较麻烦，可以设置成根据时间的吗
