### ISSUE TITLE
弹幕走着会变成只有一条道

### ISSUE THREAD

**Issue by jtyang** [hpdx/DanmukuLight#3]
开始两条道走，走着走着会变成只有一条道显示弹幕，很大概率出现这种情况

**Comment by hpdx** [comment]
@jtyang 
1、目前每条弹幕选择弹道是随机的（比如你有3条弹道，新添加的弹幕可能是在这三条弹道中的任一条上）。
2、你说的那种情况是存在的，不过目前我没有好的思路去解决它。
3、我有考虑过的：在添加一条弹幕到弹道上之前，先判断下每条弹道上的弹幕数量，之后选择弹幕数量少的弹道，将新的弹幕添加上去，但是每条弹幕的长度是不确定，所以这种思路我试了之后，放弃了。
4、你可以下载源码，按你的思路优化下。
在源码中找DanMuDispatcher这个类中的dispatch(DanMuModel danMuView, DanMuChannel[] danMuChannels) 方法，你可以修改dispatch方法中的具体实现
