### ISSUE TITLE
关于view和surfaceView选择的问题

### ISSUE THREAD

**Issue by iostyle** [hpdx/DanmukuLight#39]
最近打算将直播间的弹幕替换为surfaceView实现，为什么ReadMe上写的直播间推荐使用view的方式呢，请教一下

**Comment by hpdx** [comment]
@iostyle  你试一下就知道问题所在了，直播画面渲染的容器使用SurfaceView，弹幕层是盖在直播容器上面的，两个SurfaceView叠放。我记得之前测试时，会导致画面卡顿、抖动，目前的新版本还是否会存在这类问题，我不确定。
