### ISSUE TITLE
hi，在使用该库的时候发现弹屏的位置有点奇怪，就是那两行，可以设置在一定区域的随机位置出现吗？

### ISSUE THREAD

**Issue by ShineBright2015** [hpdx/DanmukuLight#4]

**Comment by hpdx** [comment]
@ShineBright2015 可以设置多个弹道的，每个高度为40dp
<img width="559" alt="2017-03-20 1 27 38" src="https://cloud.githubusercontent.com/assets/10386453/24089428/83032be6-0d71-11e7-855e-0182928056b8.png">

1、“在一定区域的”，可以通过设置弹道数及View的位置；
2、“随机位置”，这个满足不了
