### ISSUE TITLE
你好!研究了你写的代码,封装了多层,太厉害了,都看晕了,怎么能设置显示3行弹幕呢?默认的是两行,谢谢!

### ISSUE THREAD

**Issue by YiBeeM** [hpdx/DanmukuLight#5]

**Comment by YiBeeM** [comment]
知道了,原来是通过设置控件的高度.

**Comment by hpdx** [comment]
@YiBeeM 
<img width="559" alt="2017-03-20 1 27 38" src="https://cloud.githubusercontent.com/assets/10386453/24089390/24aaa27c-0d71-11e7-83bb-ae500ca129c7.png">

我写的很清楚呀
