### ISSUE TITLE
怎么把弹幕放在任意位置？

### ISSUE THREAD

**Issue by cadaba** [hpdx/DanmukuLight#6]
大神，我用DanMuParentView作为DanMuView的根布局，DanMuView的高度为80dp，为什么弹幕有大部分都会隐藏呢？（DanMuView的高度不设置全屏，很多弹幕都不会出现在DanMuView 80dp高度的弹道里面），如何解决呢？在线等

**Comment by hpdx** [comment]
@cadaba 我有提供demo的呀，DanMuParentView就是一个View，你可以放置到任意位置，比如下面的布局文件：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/sdv_cover"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:actualImageScaleType="centerCrop"/>

    <com.anbetter.danmuku.DanMuParentView
        android:id="@+id/dpv_broadcast"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="30dp">

        <com.anbetter.danmuku.DanMuView
            android:id="@+id/danmaku_container_broadcast"
            android:layout_width="match_parent"
            android:layout_height="80dp"/>

    </com.anbetter.danmuku.DanMuParentView>

    <com.anbetter.danmuku.DanMuParentView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="300dp">

        <com.anbetter.danmuku.DanMuView
            android:id="@+id/danmaku_container_room"
            android:layout_width="match_parent"
            android:layout_height="80dp"/>

    </com.anbetter.danmuku.DanMuParentView>

    <Button
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="20dp"
        android:layout_marginLeft="15dp"
        android:text="显示用户发送的弹幕"/>

    <Button
        android:id="@+id/button2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="20dp"
        android:layout_marginRight="20dp"
        android:text="显示系统消息弹幕"/>

</RelativeLayout>

**Comment by cadaba** [comment]
恩，我这也看了您的demo，我的DanMuParentView，写在FrameLayout里面的，但是按照您的demo的写法 还是会出现随机弹幕会满屏的跑，不能每条弹幕都出现在写死的弹道里....求指教啊

**Comment by hpdx** [comment]
@cadaba DanMuView的高度为80dp，就只有两条弹道，每条高度为40dp，为什有的弹幕发了没看见呢？原因是，当前设置的弹道是显示不下那么多弹幕的，等当前弹道能容纳新的新的弹幕时，后续的弹幕就会出现。（有一个弹幕队列的）

**Comment by hpdx** [comment]
@cadaba 满屏跑，是因为DanMuView你设置的高度有问题。
