### ISSUE TITLE
你好,每条弹道的高度目前为40dp具体是什么含义?

### ISSUE THREAD

**Issue by zzh1026** [hpdx/DanmukuLight#8]
是不是就是说弹道的高度就是确定的40,我设置margintop和paddingtop都是40减去这个值以后的实际高度?

**Comment by hpdx** [comment]
目前弹道的高度是固定的40dp，后面我会改成可以动态修改其高度的，谢谢。

**Comment by Zhangxd77** [comment]
我想把高度改高一点，是直接把40这里改其他就可以吗，还有其他地方需要改吗
