### ISSUE TITLE
持续添加弹幕的时候会导致弹幕一直gc，会对弹幕移动造成一点卡顿

### ISSUE THREAD

**Issue by wangchang163** [hpdx/DanmukuLight#9]

**Comment by hpdx** [comment]
这个暂时，没想到好的解决办法，你要很频繁的添加弹幕，我只能不停的GC了，不然难道要崩溃？正常使用是没有问题的，除非你自己用代码写了个for循环在测试。这个弹幕库目前用在我们公司的直播项目中，已使用一年多。
